# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.3-alpine
    container_name: db-library
    restart: no
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=library
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  pgdata:
